services:
  - type: web
    name: shynex-pdf-service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PDF_API_SECRET
        value: shynex-pdf-2026-secret
